FROM maven:3.9.8-eclipse-temurin-21-alpine AS build
ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME
ADD . $HOME
RUN --mount=type=cache,target=/root/.m2 mvn -f $HOME/pom.xml package -Dmaven.test.skip=true

FROM eclipse-temurin:21-jdk-alpine
COPY --from=build /usr/app/target/*.jar app.jar
COPY marca_etec.png marca_etec.png
COPY marca_um.png marca_um.png
COPY medios.pdf medios.pdf
ENTRYPOINT ["java","-jar","/app.jar"]
